name: bday counter

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - name: Install python requirements
        run: |
          pip install python-telegram-bot pyrogram tgcrypto
      - name: Check Configuration
        run: |
          function required () { if ! [[ "$1" ]]; then echo "$2 variable can't be null." && exit 1; fi }
          required "${{ steps.config.outputs.date }}" "DATE secret"
          required "${{ steps.config.outputs.month }}" "MONTH secret"
          required "${{ steps.config.outputs.year }}" "YEAR config"
          required "${{ steps.config.outputs.tg_id }}" "TG_ID config"
          required "${{ steps.config.outputs.username }}" "USERNAME config"
          required "${{ secrets.bot_token }}" "BOT_TOKEN config"
      - name: initialization
        continue-on-error: true
        run: |
          git config --global user.name ${{ secrets.gh_name }}
          git config --global user.email ${{ secrets.gh_mail }}
          git config --global credential.helper store
          echo "https://${{ secrets.gh_name }}:${{ secrets.gh_token }}@github.com" > ~/.git-credentials
      - name: Calculation + Telegram notify
        timeout-minutes: 350
        continue-on-error: true
        env:
              DATE: "${{ steps.config.outputs.date }}"
              MONTH: "${{ steps.config.outputs.month }}"
              YEAR: "${{ steps.config.outputs.year }}"
              TG_ID: "${{ steps.config.outputs.tg_id }}"
              USERNAME: "${{ steps.config.outputs.username }}"
              TOKEN: "${{ secrets.BOT_TOKEN }}"
        run: |
          python basics.py
      - name: Loop
        continue-on-error: true
        run: |
              git clone https://github.com/ping2109/birthday_counter reloop
              cd reloop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GH_TOKEN }}@github.com/ping2109/birthday_counter HEAD:main
