name: ping2109GSIs Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load Configuration
        uses: falti/dotenv-action@v0.2.5
        id: config
        with:
          path: config.env
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.5'
      - name: Install python requirements
        run: |
          pip install python-telegram-bot pyrogram tgcrypto
      - name: Check Configuration
        run: |
          required "${{ steps.config.outputs.date }}" "DATE secret"
          required "${{ steps.config.outputs.month }}" "MONTH secret"
          required "${{ steps.config.outputs.year }}" "YEAR config"
          required "${{ steps.config.outputs.tg_id }}" "TG_ID config"
          required "${{ secrets.bot_token }}" "BOT_TOKEN config"
      - name: Calculation + Telegram notify
        continue-on-error: true
        env:
              DATE: "${{ steps.config.outputs.date }}"
              MONTH: "${{ steps.config.outputs.month }}"
              YEAR: "${{ steps.config.outputs.year }}"
              TG_ID: "${{ steps.config.outputs.tg_id }}"
              TOKEN: "${{ secrets.BOT_TOKEN }}"
        run: |
          python basics.py
